######################################################################
# Automatically generated by qmake (3.0) Fri Apr 14 02:35:19 2017
######################################################################

TEMPLATE = app
TARGET = LinearAlgebra
INCLUDEPATH += .
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
# Input
HEADERS += mainwindow.h ui_mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
